Repository DronCode/ReHitman, pull requests merged in 2020-03, with the labels that each got.

#40 ZHM3Actor API reverse
  HM3CoreKill/HM3CoreKill/HM3CoreKill.vcxproj
  HM3CoreKill/HM3CoreKill/HM3CoreKill.vcxproj.filters
  HM3CoreKill/HM3CoreKill/ck/HM3Direct3D.cpp
  HM3CoreKill/HM3CoreKill/ck/HM3Direct3D.h
  HM3CoreKill/HM3CoreKill/ck/HM3Game.cpp
  HM3CoreKill/HM3CoreKill/ck/HM3Game.h
  HM3CoreKill/HM3CoreKill/ck/HM3Hooks.cpp
  HM3CoreKill/HM3CoreKill/ck/HM3Hooks.h
  HM3CoreKill/HM3CoreKill/ck/HM3InGameTools.cpp
  HM3CoreKill/HM3CoreKill/ck/HM3InGameTools.h
  HM3CoreKill/HM3CoreKill/ck/HM3Offsets.h
  HM3CoreKill/HM3CoreKill/sdk/ZHM3Actor.h
  HM3CoreKill/HM3CoreKill/sdk/ZHM3Hitman3.h
  HM3CoreKill/HM3CoreKill/sdk/ZHM3Item.h
  HM3CoreKill/HM3CoreKill/sdk/ZHM3WeaponItem.h
  HM3CoreKill/HM3CoreKill/sdk/ZLinkedListNodeBase.h
  HM3CoreKill/HM3CoreKill/sdk/ZSysInputWintel.h
  HM3CoreKill/HM3CoreKill/sdk/actions/ZHitmanActionPickLock.h
  HM3CoreKill/HM3CoreKill/sdk/game/ZHM3MovementGuideToMatPos.h
  HM3CoreKill/HM3CoreKill/sdk/game/ZHM3WeaponsControl.h
  HM3CoreKill/HM3CoreKill/sdk/game/ZM13PosController.h
  HM3CoreKill/HM3CoreKill/sdk/render/ZLoader_Sequence_Wintel_D3D.h
Labels: reverse component

#46 New Launcher Icon
  Launcher/Launcher.sln
  Launcher/Launcher.vcxproj
  Launcher/Launcher.vcxproj.filters
  Launcher/headers/resource.h
  Launcher/icons/icon.ico
  Launcher/resources/Resource.rc
Labels: cleanup, feature request

#44 ZPathFollower, ZHumanBoid, actors movement system and other core components
  HM3CoreKill/HM3CoreKill/HM3CoreKill.vcxproj
  HM3CoreKill/HM3CoreKill/HM3CoreKill.vcxproj.filters
  HM3CoreKill/HM3CoreKill/ck/HM3CutSequencesRegistry.cpp
  HM3CoreKill/HM3CoreKill/ck/HM3CutSequencesRegistry.h
  HM3CoreKill/HM3CoreKill/ck/HM3Direct3D.cpp
  HM3CoreKill/HM3CoreKill/ck/HM3Game.cpp
  HM3CoreKill/HM3CoreKill/ck/HM3Game.h
  HM3CoreKill/HM3CoreKill/ck/HM3GamepadSupport.cpp
  HM3CoreKill/HM3CoreKill/ck/HM3GamepadSupport.h
  HM3CoreKill/HM3CoreKill/ck/HM3Hooks.cpp
  HM3CoreKill/HM3CoreKill/ck/HM3Hooks.h
  HM3CoreKill/HM3CoreKill/ck/HM3InGameTools.cpp
  HM3CoreKill/HM3CoreKill/ck/HM3InGameTools.h
  HM3CoreKill/HM3CoreKill/ck/HM3Offsets.h
  HM3CoreKill/HM3CoreKill/sdk/CCutSequence.h
  HM3CoreKill/HM3CoreKill/sdk/CTelePortList.cpp
  HM3CoreKill/HM3CoreKill/sdk/CTelePortList.h
  HM3CoreKill/HM3CoreKill/sdk/REFTAB32.h
  HM3CoreKill/HM3CoreKill/sdk/ZActionManager.h
  HM3CoreKill/HM3CoreKill/sdk/ZCar.h
  HM3CoreKill/HM3CoreKill/sdk/ZDirect3DDevice.h
  HM3CoreKill/HM3CoreKill/sdk/ZEngineDatabase.cpp
  HM3CoreKill/HM3CoreKill/sdk/ZEngineDatabase.h
  HM3CoreKill/HM3CoreKill/sdk/ZGUI.h
  HM3CoreKill/HM3CoreKill/sdk/ZGUIBase.h
  HM3CoreKill/HM3CoreKill/sdk/ZGameControlWintel.h
  HM3CoreKill/HM3CoreKill/sdk/ZGameGlobals.h
  HM3CoreKill/HM3CoreKill/sdk/ZHM3Actor.h
  HM3CoreKill/HM3CoreKill/sdk/ZHM3Camera.h
  HM3CoreKill/HM3CoreKill/sdk/ZHM3CameraClass.h
  HM3CoreKill/HM3CoreKill/sdk/ZHM3GameData.h
  HM3CoreKill/HM3CoreKill/sdk/ZHM3Hitman3.h
  HM3CoreKill/HM3CoreKill/sdk/ZHM3LevelControl.h
  HM3CoreKill/HM3CoreKill/sdk/ZHM3MenuElements.h
  HM3CoreKill/HM3CoreKill/sdk/ZHM3MenuFactory.h
  HM3CoreKill/HM3CoreKill/sdk/ZHumanBoid.h
  HM3CoreKill/HM3CoreKill/sdk/ZOnlineElements.h
  HM3CoreKill/HM3CoreKill/sdk/ZPathFollower.h
  HM3CoreKill/HM3CoreKill/sdk/ZSTD.h
  HM3CoreKill/HM3CoreKill/sdk/ZStandardMenuFactory.h
  HM3CoreKill/HM3CoreKill/sdk/ZSysInputWintel.h
  HM3CoreKill/HM3CoreKill/sdk/ZSysMem.h
  HM3CoreKill/HM3CoreKill/sdk/ZWINDOW.h
  HM3CoreKill/HM3CoreKill/sdk/ZWINDOWS.h
  HM3CoreKill/HM3CoreKill/sdk/ZXMLGUISystem.h
Labels: debug menu, reverse component
